version: '3.6'
services: 

  reddcoin-logger:
    container_name: reddcoin-logger
    image: shroomlife/reddcoin-logger:latest
    build: .
    env_file: .env

  db:
    container_name: db
    image: mariadb:latest
    env_file: .env
    # volumes:
    #   - "/root/dbdata:/var/lib/mysql"
    ports:
      - "3306:3306"